### ISSUE TITLE
Add 1.6 since trunk is 1.7 now

### ISSUE THREAD

**Issue by Fale** [cbonte/haproxy-dconv#11]
As title

**Comment by PikachuEXE** [comment]
It seems to have been added now, close?

**Comment by cbonte** [comment]
Hi, since an issue is open, I prefer to keep it in this state.
I did the strict minimum to have a 1.6 version of the documentation, but I have still a lot of work to do to consider we have a stable documentation. Indeed, the documentation was split in several files.

At least, I intend to :
- generate a documentation for each file
- provide a navigation menu to go from one file to another
- enhance the search field to manage the keywords from the other files
- ...

**Comment by cbonte** [comment]
At last, everything is ready, I can close the issue ;-)
